RUNWAYS = [
    {
        'id': '8',
        'lat': 33.440861, 'lon': -112.029794,
        'heading': 78,
        'length_ft': 11489, 'width_ft': 150,
        'displaced_threshold_ft': 898,
        'papi': True,
        'approach': 'ILS/DME',
        'markings': 'precision',
        'declared_distances': {'TORA': 11489, 'TODA': 11489, 'ASDA': 11489, 'LDA': 10591},
        'obstructions': [{'type': 'building', 'height_ft': 66, 'distance_ft': 3020, 'lateral_offset_ft': 503, 'slope': 42}],
        'traffic_pattern': 'left',
        'approach_lights': 'MALSF: 1,400 foot medium intensity approach lighting system with sequenced flashers',
        'runway_end_lights': 'no',
        'touchdown_point': 'yes, no lights'
    },
    {
        'id': '26',
        'lat': 33.440823, 'lon': -111.992136,
        'heading': 258,
        'length_ft': 11489, 'width_ft': 150,
        'displaced_threshold_ft': 0,
        'papi': True,
        'approach': 'ILS/DME',
        'markings': 'precision',
        'declared_distances': {'TORA': 11489, 'TODA': 11489, 'ASDA': 11489, 'LDA': 11489},
        'obstructions': [{'type': 'road', 'height_ft': 9, 'distance_ft': 905, 'lateral_offset_ft': 540, 'slope': None}],
        'traffic_pattern': 'right',
        'approach_lights': 'MALSF: 1,400 foot medium intensity approach lighting system with sequenced flashers',
        'runway_end_lights': 'yes',
        'touchdown_point': 'yes, no lights'
    },
    {
        'id': '07L',
        'lat': 33.431058, 'lon': -112.027102,
        'heading': 78,
        'length_ft': 10300, 'width_ft': 150,
        'displaced_threshold_ft': 0,
        'papi': True,
        'approach': 'ILS/DME',
        'markings': 'precision',
        'declared_distances': {'TORA': 10300, 'TODA': 10300, 'ASDA': 10300, 'LDA': 10300},
        'obstructions': [{'type': 'pole', 'height_ft': 62, 'distance_ft': 2958, 'lateral_offset_ft': 750, 'slope': 44}],
        'traffic_pattern': 'right',
        'approach_lights': 'MALSR: 1,400 foot medium intensity approach lighting system with runway alignment indicator lights',
        'runway_end_lights': 'no',
        'touchdown_point': 'yes, no lights'
    },
    {
        'id': '25R',
        'lat': 33.431036, 'lon': -111.993345,
        'heading': 258,
        'length_ft': 10300, 'width_ft': 150,
        'displaced_threshold_ft': 0,
        'papi': True,
        'approach': 'ILS/DME',
        'markings': 'precision',
        'declared_distances': {'TORA': 10300, 'TODA': 10300, 'ASDA': 10300, 'LDA': 10300},
        'obstructions': [{'type': 'antenna', 'height_ft': 416, 'distance_ft': 17582, 'lateral_offset_ft': 600, 'slope': 41}],
        'traffic_pattern': 'left',
        'approach_lights': 'MALSR: 1,400 foot medium intensity approach lighting system with runway alignment indicator lights',
        'runway_end_lights': 'no',
        'touchdown_point': 'yes, no lights'
    },
    {
        'id': '07R',
        'lat': 33.428859, 'lon': -112.027102,
        'heading': 78,
        'length_ft': 7800, 'width_ft': 150,
        'displaced_threshold_ft': 0,
        'papi': True,
        'approach': 'ILS/DME',
        'markings': 'precision',
        'declared_distances': {'TORA': 7800, 'TODA': 7800, 'ASDA': 7800, 'LDA': 7800},
        'obstructions': [{'type': 'pole', 'height_ft': 33, 'distance_ft': 900, 'lateral_offset_ft': 640, 'slope': 20}],
        'traffic_pattern': 'left',
        'approach_lights': 'MALSR: 1,400 foot medium intensity approach lighting system with runway alignment indicator lights',
        'runway_end_lights': 'no',
        'touchdown_point': 'yes, no lights'
    },
    {
        'id': '25L',
        'lat': 33.428843, 'lon': -112.001539,
        'heading': 258,
        'length_ft': 7800, 'width_ft': 150,
        'displaced_threshold_ft': 0,
        'papi': True,
        'approach': 'ILS/DME',
        'markings': 'precision',
        'declared_distances': {'TORA': 7800, 'TODA': 7800, 'ASDA': 7800, 'LDA': 7800},
        'obstructions': [{'type': 'antenna', 'height_ft': 424, 'distance_ft': 20059, 'lateral_offset_ft': 1193, 'slope': 46}],
        'traffic_pattern': 'left',
        'approach_lights': 'MALSR: 1,400 foot medium intensity approach lighting system with runway alignment indicator lights',
        'runway_end_lights': 'no',
        'touchdown_point': 'yes, no lights'
    }
]